### PR TITLE
section2 week3

### PR DESCRIPTION
**Pull request by qh70**
http://140.112.3.5:3000/
http://140.112.3.5:3000/attraction/10

### CODE REVIEW

**Comment by qh70** [comment]
http://54.236.231.32:3000
http://54.236.231.32:3000/attraction/26

**Comment by cwpeng** [comment]
Wait your updates.

**Comment by qh70** [comment]
Hello,teacher Peng Peng
I've corrected the problems of color for choosing time,dots margin,line align and screen for less than 600px,
please check for me,thank you :)

http://54.236.231.32:3000/
http://54.236.231.32:3000/attraction/26

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
