### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by qh70**
http://54.236.231.32:3000/api/attractions?page=1
[http://54.236.231.32:3000/api/attractions?page=0&keyword=藝術
http://54.236.231.32:3000/api/attraction/100

彭彭老師您好 這是我這禮拜的作業 我的邀請碼是WH02029
名字 : 黃啟元      Email : qh7047789@gmail.com
老師辛苦了

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Use LIMIT statement in your SQL query to do range selection.
2. Get count of rows in every request.

Ask me to review again after fixing issues.

**Comment by qh70** [comment]
http://54.236.231.32:3000/api/attractions?page=1
http://54.236.231.32:3000/api/attractions?page=0&keyword=藝術
http://54.236.231.32:3000/api/attraction/100

I have changed statement in my SQL query by using LIMIT and get count of rows in request,please review for me,thank you so mush!

**Review by cwpeng — CHANGES_REQUESTED** [review]
You can use `SELECT count(*) FROM ... WHERE` to get count of data even if there is a keyword filter. Don't try to get all results just for the length of data, like SQL query below:
```
			sql_keyword="SELECT `id` FROM `sub_data` WHERE `name` LIKE '%"+keyword+"%'"
			# 取得有 keyword 的 id
			my_cursor.execute(sql_keyword)
			keyword_result=my_cursor.fetchall() #step2. 把 keyword 放進資料庫搜尋 
```

Fix it and request me review again.

**Comment by qh70** [comment]
彭彭老師:
請問一下，

'''

sql_keyword="SELECT `id` FROM `sub_data` WHERE `name` LIKE '%"+keyword+"%'"

# 取得有 keyword 的 id

my_cursor.execute(sql_keyword)

keyword_result=my_cursor.fetchall() #step2. 把 keyword 放進資料庫搜尋

...

(加下面的一大段)

'''



那段是被我註解掉的，我並沒有把它們使用在app.py裡面，我想說先留著看出改前和改後的差別，也怕萬一做錯，有backup可以看。

還是說您是別的意思?

Chao-Wei Peng ***@***.***> 於 2022年3月5日 週六 下午11:49寫道：

**Review by cwpeng — APPROVED** [review]
Sorry, I miss the comment you mark. I have reviewed again, it's OK now.

But you have to resolve conflicts shown in this page before merging.

**Comment by qh70** [comment]
I've done the task and merged it,thank you for reminding me and patience.

Chao-Wei Peng ***@***.***> 於 2022年3月6日 週日 上午1:25寫道：

**Pull request merged**
