### PR TITLE
Assignment Part5

### PR DESCRIPTION
**Pull request by qh70**
Hello,teacher Peng Peng,
this is my assignment for part5,
please review for me,
thank you so much ^^

http://54.236.231.32:3000/
http://54.236.231.32:3000/attraction/51
http://54.236.231.32:3000/booking

### CODE REVIEW

**Comment by cwpeng** [comment]
1. In booking.html, we should redirect user to home page if not signed in.
2. We should open sign in dialog if user click 預定行程, 開始預定行程 without signing in first.
3. Separating lines should be lighter.
4. Border of inputs should align with design.

**Comment by qh70** [comment]
Hello,teacher Peng Peng:
I'm Jerry 黃啟元.
That's a little weird because I didn't see problem 1.&2. when I check,I'm going to sent you two videos on discord that recorded my test.
If there are still problems in your side,please tell me,thank you so much ^^
And I've corrected problems 3.&4.,please review for me,thanks a lot ^^

**Comment by cwpeng** [comment]
Try to use 無痕視窗 to test, it will get 500 error from your APIs. I think it's due to there is nothing in cookies when a user enter your site first time.

**Comment by qh70** [comment]
Hello,teacher Peng Peng:
I'm Jerry 黃啟元.
I've changed the logic for first time visitors in python and tested successfully,but I'm not 100% sure that I corrected the right point.
please review for me,thank you so much ^^

http://54.236.231.32:3000/
http://54.236.231.32:3000/attraction/51
http://54.236.231.32:3000/booking

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
